### PR TITLE
Create .gitignore

### PR DESCRIPTION
**Pull request by Restioson**
Added a gitignore generated with [gitignore.io](https://gitignore.io).

### CODE REVIEW

**Comment by Restioson** [comment]
The pyc's have a misleading name. They're not *really* compiled. They're still run by an interpreter.

**Comment by Restioson** [comment]
The python would be interpreted with or without them

**Comment by boynedmaster** [comment]
Hm, true. Perhaps to at least simulate a compiled CIC you can exempt cic.pyc?

**Comment by Restioson** [comment]
Perhaps. Another option is to write it in Cython and then compile it (iirc you can do that)

**Comment by boynedmaster** [comment]
CPython ends up doing the same thing, compiling it to bytecode and then interpreting it on the fly. The only option for a TRULY compiled Python CIC is to write our own compiler, which I don't think anyone will be invested enough in a joke project to do that.

**Comment by boynedmaster** [comment]
Oh, you said Cython? Not sure actually, I've never worked in it.

**Comment by Restioson** [comment]
Cython lets you compile .pyx to .c and the to native. Side note: CPython is the name for python's interpreter (written in C). Cython is an alternative implementation which can compile Cython code (slightly different) to C code.

**Comment by Restioson** [comment]
Never worked in it either. Doesn't look too hard... I'd be willing to code it in and perhaps convert existing code.

**Comment by boynedmaster** [comment]
That'd be good, but maybe something for when the spec is nearing or at completion. The code for the Python CIC might be radically different at that stage.

**Comment by Restioson** [comment]
Additionally, programs can compile to pyx and then to c, perhaps?

**Comment by DyingEcho** [comment]
> The only option for a TRULY compiled Python CIC is to write our own compiler, which I don't think anyone will be invested enough in a joke project to do that.

People are. So far I believe we have two people working on it.

**Comment by DyingEcho** [comment]
Also, the `.pyc` files can be made by the developer coding in PyHP++# - we don't need to. This repository is for the code of the CIC, not the CIC itself - compiled binaries can be attached to releases.

**Comment by boynedmaster** [comment]
I am working on a CIC, it's just not truly compiled because Python isn't compiled. What I meant by a TRULY compiled CIC is a compiled binary.

**Comment by boynedmaster** [comment]
By the way, I like the .gitignore, can someone merge it?

**Comment by Restioson** [comment]
I propose the CIC written in Cython so it can actually be compiled.

**Comment by boynedmaster** [comment]
Is Python code not backwards compatible with Cython?

**Comment by Restioson** [comment]
It is compatible, however it is better to convert the Python to more C like constructs, e.g structs, unions, typed variables, pointers.

**Comment by boynedmaster** [comment]
True. At the moment though, I'm pausing development until the spec is complete and we have a PEG file, because the library I'm using right now is constantly getting in my way.

**Comment by Restioson** [comment]
What library are you using?

**Comment by Kampfkarren** [comment]
Arpeggio.

**Comment by Restioson** [comment]
What for?

**Comment by Restioson** [comment]
We could transpile it to a natively compiled language and then compile the transpiled version

**Comment by Kampfkarren** [comment]
No no, my problem is Arpeggio's lack of good indentation detection (the lexer process).

**Comment by Restioson** [comment]
No, I was being unrelated there :p

**Comment by Kampfkarren** [comment]
Oh, yea that's a possibility. I'd love to see PyHP++# as a backend and frontend for a website.

**Comment by Restioson** [comment]
please no

**Comment by Kampfkarren** [comment]
https://github.com/erezsh/lark - This seems to be the only Python PEG library that supports significant whitespace, I'm going to play around with this.

**Pull request merged**
